// Thông tin phân khu B站 - cập nhật theo tài liệu API chính thức, phân khu chính cấp 1
export const BILIBILI_PARTITIONS = [
  { id: 1, name: "Hoạt hình" },
  { id: 4, name: "Trò chơi" },
  { id: 8, name: "Video nhại" },
  { id: 3, name: "Âm nhạc" },
  { id: 129, name: "Khiêu vũ" },
  { id: 181, name: "Điện ảnh & TV" },
  { id: 5, name: "Giải trí" },
  { id: 36, name: "Kiến thức" },
  { id: 188, name: "Công nghệ & Số hóa" },
  { id: 202, name: "Tin tức" },
  { id: 76, name: "Ẩm thực" },
  { id: 138, name: "Kịch ngắn" },
  { id: 176, name: "Ô tô" },
  { id: 155, name: "Thời trang & Làm đẹp" },
  { id: 235, name: "Thể thao" },
  { id: 75, name: "Động vật" },
  { id: 21, name: "vlog" },
  { id: 162, name: "Hội họa" },
  { id: 207, name: "Trí tuệ nhân tạo" },
  { id: 208, name: "Nội thất & Bất động sản" },
  { id: 209, name: "Ngoài trời & Thời trang" },
  { id: 164, name: "Thể hình" },
  { id: 161, name: "Thủ công" },
  { id: 165, name: "Du lịch" },
  { id: 158, name: "Nông thôn" },
  { id: 159, name: "Gia đình & Trẻ em" },
  { id: 160, name: "Sức khỏe" },
  { id: 163, name: "Tình cảm" },
  { id: 22, name: "Sở thích cuộc sống" },
  { id: 23, name: "Kinh nghiệm sống" }
]
